[package]
name = "engine"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow = "1.0.99"
bytemuck = "1.23.2"
glam = "0.30.5"
log = "0.4.28"
pollster = "0.4.0"
rand = "0.9.2"
wgpu = "26.0.1"
winit = "0.30.12"
